import { StyleSheet } from "react-native";
import { colors } from "../../theme";
import { wp, hp, ms, vs } from "../../utils/responsive";

export const clientDetailsStyles = StyleSheet.create({
  // Layout / background
  safeArea: { flex: 1, backgroundColor: colors.background },
  viewport: {
    flex: 1,
    paddingHorizontal: wp(4),
    paddingBottom: hp(2),
  },

  // Top bar (back arrow + date badge)
  topbar: {
    position: "absolute",
    top: hp(0.6),
    left: 0,
    right: 0,
    height: vs(72),
    zIndex: 20,
  },
  backButton: {
    position: "absolute",
    left: wp(4),
    top: 0,
   
    justifyContent: "center",
    alignItems: "center",
  },
  dateBadge: {
    position: "absolute",
    right: wp(4),
    top: 0,
 
    // backgroundColor: "rgba(18, 12, 28, 0.92)",
    borderWidth: 1,

    alignItems: "center",
    justifyContent: "center",
    gap: vs(2),
  },
  dateBadgeDay: { fontSize: ms(15), color: "#FFFFFF", fontWeight: "700" },
  dateBadgeNumber: { fontSize: ms(17), color: "#FFFFFF", fontWeight: "800" },

  // Profile
  profile: {
    alignItems: "center",
    // marginTop: hp(-10) + vs(72) + vs(5),
    marginBottom: vs(8),
  },
  avatarWrapOuter: { width: ms(88), height: ms(88), padding: ms(3), borderRadius: ms(46) },
  avatarWrap: {
    flex: 1,
    borderRadius: ms(46),
    borderWidth: 2,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  avatar: { width: "100%", height: "100%", borderRadius: ms(46) },
  avatarPlaceholder: { backgroundColor: "#333", justifyContent: "center", alignItems: "center" },
  avatarInitial: { fontSize: ms(28), color: "#FFFFFF", fontWeight: "800" },

  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ms(10),
    flexWrap: "wrap",
  },
  miniTools: { flexDirection: "row", gap: ms(8) },
  toolBox: {
    width: ms(26),
    height: ms(26),
    borderRadius: ms(8),
    borderWidth: 1,
    backgroundColor: "rgba(21,10,33,0.95)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  toolCount: {
    position: "absolute",
    backgroundColor: colors.bg,
    right: ms(-5),
    bottom: vs(-5),
    color: "#FFFFFF",
    fontSize: ms(11),
    fontWeight: "800",
  },

  namePhone: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(10),
    flexWrap: "wrap",
    justifyContent: "center",
  },
  nameText: { color: "#FFFFFF", fontSize: ms(17), fontWeight: "800" },
  subText: { color: "rgba(255,255,255,0.9)", fontSize: ms(13), fontWeight: "600" },
  menuDots: { color: "#fff", fontSize: ms(18), opacity: 0.8 },

  focusText: {
    marginTop: vs(6),
    color: "rgba(255,255,255,0.88)",
    fontSize: ms(13),
    fontWeight: "600",
    textAlign: "center",
  },

  // Progress
  progress: { width: "100%", paddingHorizontal: wp(6), marginTop: vs(5) },
  progressBar: {
    height: vs(4),
    borderRadius: ms(999),
    backgroundColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: ms(999),
    backgroundColor: colors.primary,
  },
  progressLabel: {
    marginTop: vs(5),
    textAlign: "center",
    color: "#FFFFFF",
    fontSize: ms(14),
    fontWeight: "700",
  },

  // Cards area
  cardsContainer: { width: "100%", marginTop: vs(4), flex: 1, minHeight: 0 },
  /** Measured for modal: Consultation → Client Notes (excludes Plan/Complete row). */
  mainCardsBand: {
    width: "100%",
  },
  sectionWrap: { width: "100%" },
  bottomActionRow: {
    flexDirection: "row",
    gap: ms(12),
    width: "100%",
  },
  bottomBtn: {
    height: hp(6.2),
    borderRadius: ms(999),
    borderWidth: 1,
    backgroundColor: "rgba(14,8,21,0.95)",
    paddingHorizontal: ms(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ms(8),
    overflow: "hidden",
  },
  bottomBtnGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: ms(999),
    borderWidth: 2,
  },
  bottomBtnText: {
    color: "#FFFFFF",
    fontSize: ms(12),
    fontWeight: "800",
  },
  sectionTitlePill: {
    position: "absolute",
    alignSelf: "center",
    top: vs(-9),
    zIndex: 3,
    paddingHorizontal: ms(15),
    paddingVertical: vs(4),
    borderRadius: ms(999),
    borderWidth: 1,
    backgroundColor:colors.bg,
  },
  sectionTitleText: { color: "#FFFFFF", fontSize: ms(11), fontWeight: "800", textAlign: "center" },
  sectionCard: {
    borderWidth: 2,
    borderRadius: ms(12),
    paddingTop: vs(6),
    paddingHorizontal: wp(1.7),
    backgroundColor: colors.bg,
    overflow: "hidden",
  },
  sectionGlowPulse: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: ms(24),
    borderWidth: 2,
  },

  // Consultation
  consultHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  consultHeaderText: { color: "#FFFFFF", fontSize: ms(12), fontWeight: "700" },
  divider: { height: 1, backgroundColor: "rgba(255,255,255,0.1)", marginVertical: vs(0.5) },
  bodyText: {
    color: "#FFFFFF",
    fontSize: ms(11),
    lineHeight: ms(14),
    fontWeight: "600",
    height: hp(9),
  },
  footnote: { color: "rgba(255,255,255,0.78)", fontSize: ms(11), fontStyle: "italic", fontWeight: "500" },

  // Services + maintain rows
  servicesCardBody: {
    flex: 1,
    minHeight: 0,
    justifyContent: "flex-start",
  },
  servicesUsedScroll: {
    maxHeight: hp(9),
    width: "100%",
    paddingHorizontal: ms(4),
  },
  serviceItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp(0.9),
  },
  serviceLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(10),
    flex: 1,
    minWidth: 0,
  },
  bulletDot: {
    width: ms(10),
    height: ms(10),
    borderRadius: ms(5),
    backgroundColor: colors.primary,
  },
  serviceName: { color: "#FFFFFF", fontSize: ms(12), fontWeight: "700", flex: 1, minWidth: 0 },
  priceText: { color: "#FFFFFF", fontSize: ms(12), fontWeight: "800" },

  enhanceCard: {
    marginTop: vs(8),
    borderRadius: ms(8),
    borderWidth: 1,
    paddingTop: vs(10),
    paddingBottom: vs(8),
    paddingHorizontal: ms(6),
    minHeight: hp(6),
    backgroundColor: colors.bg,
  },
  enhanceCardDocked: {
    marginTop: "auto",
    marginBottom: vs(5),
  },
  enhancePill: {
    position: "absolute",
    alignSelf: "center",
    top: vs(-12),
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.6),
    borderRadius: ms(999),
    borderWidth: 1,
    backgroundColor:colors.bg,
  },
  enhancePillText: { color: "#FFFFFF", fontSize: ms(11), fontWeight: "800" },
  checkCircle: {
    width: ms(18),
    height: ms(18),
    borderRadius: ms(9),
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: vs(2),
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  enhanceTextWrap: { flex: 1, minWidth: 0 },
  enhanceTitle: { color: "#FFFFFF", fontSize: ms(12), fontWeight: "700" },
  enhanceSubtitle: { color: "rgba(255,255,255,0.88)", fontSize: ms(12), marginTop: vs(2), fontWeight: "600" },

  groupLabel: { color: "rgba(255,255,255,0.82)", fontSize: ms(11), fontWeight: "700", marginBottom: vs(6) },
  productItemRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  productLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(12),
    flex: 1,
    minWidth: 0,
  },
  productImg: { width: ms(42), height: vs(52), borderRadius: ms(10), backgroundColor: "rgba(255,255,255,0.08)" },
  productName: { color: "#FFFFFF", fontSize: ms(13), fontWeight: "700", flex: 1, minWidth: 0 },
  groupSpacer: { height: vs(12) },

  // Maintain this look (2 dynamic rows; placeholders always visible)
  maintainStack: {
    flex: 1,
    minHeight: 0,
    width: "100%",
  },
  maintainUsedBlock: {
    width: "100%",
    flex: 1,
    minHeight: 0,
  },
  maintainUsedScroll: {
    maxHeight: hp(10),
  },
  maintainRetailLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(8),
    marginBottom: vs(4),
  },
  retailPinkDot: {
    width: ms(8),
    height: ms(8),
    borderRadius: ms(4),
  },
  retailProductThumb: {
    width: ms(40),
    height: ms(40),
    borderRadius: ms(8),
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  maintainRow: {
    flexDirection: "row",
    gap: ms(10),
    width: "100%",
    alignItems: "flex-start",
  },
  productThumb: {
    width: wp(10),
    height: hp(5),
    borderRadius: ms(8),
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  maintainRowContent: {
    flex: 1,
    minWidth: 0,
  },
  maintainDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.16)",
    marginTop: vs(10),
    marginBottom: vs(10),
  },
  maintainRowPlain: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ms(10),
  },
  maintainRowChecked: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(10),
    marginTop: vs(3),
  },
  maintainCheckCircle: {
    width: ms(20),
    height: ms(20),
    borderRadius: ms(10),
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  maintainRowText: {
    flex: 1,
    minWidth: 0,
    color: "#FFFFFF",
    fontSize: ms(12),
    fontWeight: "600",
  },
  maintainRowPrice: {
    color: "#FFFFFF",
    fontSize: ms(12),
    fontWeight: "800",
  },

  tinyRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: vs(8) },
  tinyLeft: { flexDirection: "row", alignItems: "center", gap: ms(8), flex: 1, minWidth: 0 },
  neutralCheck: {
    width: ms(18),
    height: ms(18),
    borderRadius: ms(9),
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  tinyText: { color: "#FFFFFF", fontSize: ms(12), flex: 1, minWidth: 0, fontWeight: "600" },
  tinyPrice: { color: "#FFFFFF", fontSize: ms(12), fontWeight: "800" },

  clientNote: { color: "rgba(255,255,255,0.96)", fontSize: ms(12), lineHeight: ms(16), fontWeight: "600" },

  // Action buttons
  actionRow: { flexDirection: "row", gap: ms(12), marginTop: vs(0) },
  actionBtn: {
    flex: 1,
    minHeight: vs(30),
    borderRadius: ms(20),
    borderWidth: 1,
    backgroundColor: colors.bg,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ms(10),
  },
  actionText: { color: "#FFFFFF", fontSize: ms(13), fontWeight: "800" },

  // Overlay modal — middle column only (below progress strip, above Plan/Complete); top + bottom stay clear
  modalRoot: {
    flex: 1,
  },
  modalContentLayer: {
    flex: 1,
    minHeight: 0,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp(4),
  },
  overlayPopupWrap: {
    width: "100%",
    alignSelf: "stretch",
    flexShrink: 1,
  },
  overlayGlassInner: {
    borderRadius: ms(20),
    overflow: "hidden",
    backgroundColor: "rgba(10,12,16,0.88)",
  },
  overlayScroll: {},
  overlayScrollContent: {
    paddingHorizontal: wp(4),
    paddingTop: vs(18),
    paddingBottom: vs(16),
  },
  overlayScrollContentBandFocus: {
    paddingHorizontal: wp(3),
    paddingTop: vs(14),
  },
  overlayTitle: { color: "#FFFFFF", fontSize: ms(22), fontWeight: "800", marginBottom: vs(10) },
  overlayTitleBandFocus: {
    fontSize: ms(26),
    fontWeight: "800",
    marginBottom: vs(12),
    letterSpacing: ms(-0.2),
  },
  overlayQuickPromptsWrap: {
    marginBottom: vs(12),
  },
  /** Catalog actions (Add services / Add products) — only in section overlay, not on main cards. */
  overlayCatalogBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    gap: ms(8),
    marginBottom: vs(14),
    paddingVertical: vs(10),
    paddingHorizontal: ms(12),
    borderRadius: ms(999),
    borderWidth: 1,
    backgroundColor: colors.bg,
  },
  overlayCatalogBtnText: {
    color: "#FFFFFF",
    fontSize: ms(12),
    fontWeight: "800",
  },
  overlayPastVisitsHead: {
    marginTop: vs(16),
  },
  overlayPastVisitsBody: {
    color: "rgba(255,255,255,0.88)",
    fontSize: ms(15),
    lineHeight: ms(24),
    fontWeight: "600",
    marginBottom: vs(16),
  },
  overlayChronologyHint: {
    color: "rgba(255,255,255,0.62)",
    fontSize: ms(12),
    fontWeight: "600",
    marginBottom: vs(12),
    lineHeight: ms(17),
  },
  consultationTimelineBlock: {
    marginBottom: vs(14),
    paddingBottom: vs(12),
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  consultationTimelineBlockCurrent: {
    borderLeftWidth: ms(3),
    paddingLeft: ms(10),
    marginBottom: vs(14),
    paddingBottom: vs(12),
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.14)",
  },
  consultationTimelineDate: {
    color: "#FFFFFF",
    fontSize: ms(13),
    fontWeight: "800",
    marginBottom: vs(6),
  },
  consultationTimelineBody: {
    color: "rgba(255,255,255,0.94)",
    fontSize: ms(15),
    lineHeight: ms(24),
    fontWeight: "600",
  },
  consultationTimelineFoot: {
    color: "rgba(255,255,255,0.72)",
    fontSize: ms(12),
    fontStyle: "italic",
    marginTop: vs(8),
    lineHeight: ms(18),
    fontWeight: "600",
  },
  overlayQuickPromptsLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: ms(13),
    fontWeight: "700",
    marginBottom: vs(8),
  },
  overlayQuickPromptsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: ms(8),
    paddingVertical: vs(2),
    paddingRight: ms(4),
  },
  overlayQuickPromptPill: {
    paddingHorizontal: ms(12),
    paddingVertical: vs(8),
    borderRadius: ms(999),
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    maxWidth: wp(44),
  },
  overlayQuickPromptPillText: {
    color: "#FFFFFF",
    fontSize: ms(13),
    fontWeight: "700",
  },
  overlayHistoryLabel: { color: "rgba(255,255,255,0.75)", fontSize: ms(14), fontWeight: "700", marginBottom: vs(8) },
  overlayHistoryLabelBandFocus: {
    fontSize: ms(14),
    marginBottom: vs(10),
  },
  overlayHistoryBody: {
    color: "rgba(255,255,255,0.96)",
    fontSize: ms(15),
    lineHeight: ms(24),
    fontWeight: "600",
    marginBottom: vs(16),
  },
  overlayHistoryBodyBandFocus: {
    fontSize: ms(17),
    lineHeight: ms(28),
    color: "#FFFFFF",
    fontWeight: "600",
    marginBottom: vs(18),
  },
  overlayInputLabel: { color: "rgba(255,255,255,0.75)", fontSize: ms(14), fontWeight: "700", marginBottom: vs(8) },
  overlayInputLabelBandFocus: { fontSize: ms(14), marginBottom: vs(10) },
  overlayInput: {
    minHeight: vs(100),
    borderRadius: ms(14),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    backgroundColor: colors.bg,
    color: "#FFFFFF",
    paddingHorizontal: wp(3),
    paddingVertical: vs(12),
    fontSize: ms(16),
    lineHeight: ms(24),
    fontWeight: "600",
    marginBottom: vs(16),
    textAlignVertical: "top",
  },
  overlayInputBandFocus: {
    minHeight: vs(120),
    fontSize: ms(17),
    lineHeight: ms(28),
    paddingVertical: vs(14),
  },
  overlayActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: vs(2),
  },
  voiceBtn: {
    width: ms(52),
    height: ms(52),
    borderRadius: ms(26),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  doneBtn: {
    paddingHorizontal: wp(10),
    paddingVertical: vs(14),
    borderRadius: ms(14),
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  doneBtnText: { color: "#FFFFFF", fontSize: ms(17), fontWeight: "800" },
});
